export const SELECTED_QUESTION = 'SELECTED_QUESTION';
export const SELECTED_QUESTION_PENDING = 'SELECTED_QUESTION_PENDING';
export const SELECTED_QUESTION_REJECTED = 'SELECTED_QUESTION_REJECTED';
export const SELECTED_QUESTION_FULFILLED = 'SELECTED_QUESTION_FULFILLED';

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_PENDING = 'FETCH_QUESTIONS_PENDING';
export const FETCH_QUESTIONS_FULFILLED = 'FETCH_QUESTIONS_FULFILLED';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';

export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const FETCH_CATEGORY_QUESTIONS = 'FETCH_CATEGORY_QUESTIONS';
export const FETCH_CATEGORY_QUESTIONS_PENDING = 'FETCH_CATEGORY_QUESTIONS_PENDING';
export const FETCH_CATEGORY_QUESTIONS_FULFILLED = 'FETCH_CATEGORY_QUESTIONS_FULFILLED';
export const FETCH_CATEGORY_QUESTIONS_REJECTED = 'FETCH_CATEGORY_QUESTIONS_REJECTED';

export const FETCH_ANSWERS = 'FETCH_ANSWERS';
export const FETCH_ANSWERS_PENDING = 'FETCH_ANSWERS_PENDING';
export const FETCH_ANSWERS_FULFILLED = 'FETCH_ANSWERS_FULFILLED';
export const FETCH_ANSWERS_REJECTED = 'FETCH_ANSWERS_REJECTED';

export const LANGUAGE_SELECTED = 'LANGUAGE_SELECTED';
export const LANGUAGE_ENGLISH = 'LANGUAGE_ENGLISH';
export const LANGUAGE_SPANISH = 'LANGUAGE_SPANISH';
export const LANGUAGE_CHINESE = 'LANGUAGE_CHINESE';
