export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';
export const FETCH_QUESTIONS_PENDING = 'FETCH_QUESTIONS_PENDING';
export const FETCH_QUESTIONS_FULFILLED = 'FETCH_QUESTIONS_FULFILLED';
export const FETCH_QUESTIONS_REJECTED = 'FETCH_QUESTIONS_REJECTED';

export const FETCH_ANSWERS = 'FETCH_ANSWERS';
export const FETCH_ANSWERS_PENDING = 'FETCH_ANSWERS_PENDING';
export const FETCH_ANSWERS_FULFILLED = 'FETCH_ANSWERS_FULFILLED';
export const FETCH_ANSWERS_REJECTED = 'FETCH_ANSWERS_REJECTED';

